# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  style_check:
    working_directory: /tmp/src/style_check
    docker:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Generate environment
          command: |
            conda create -n venv python>3.6 pylint -yq
            source activate venv
            pip install flake8
      - run:
          name: Style check
          command: |
            source activate venv
            flake8 --max-line-length=79 --exclude=versioneer.py  --ignore=W503 /tmp/src/funcworks

  build:
    docker:
      - image: docker:stable-git
    working_directory: /tmp/src/funcworks
    steps:
      - run:
          name: Install parallel gzip and Python 3
          command: |
            apk add --no-cache pigz python3>3.6.0
      - run:
          name: Cleaning working Directory
          command: |
            rm -rf /tmp/src/funcworks/*
      - checkout
      - setup_remote_docker
      - run:
          name: Fetch latest release image
          no_output_timeout: 10m
          command: |
            docker pull adamkimbler/funcworks:latest
      - run:
          name: Build image
          no_output_timeout: 30m
          command: |
            THISVERSION=$( python3 -c 'import funcworks; print(funcworks.__version__)' )
            echo "Building version ${CIRCLE_TAG:-$THISVERSION}"
            docker build \
              --cache-from=adamkimbler/funcworks \
              --rm=false \
              --tag akimbler/funcworks:latest \
              --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
              --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
              --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" .
      - run:
          name: Verify executable can be run
          command: docker run --rm akimbler/funcworks:latest --help
      - run:
          name: Check version
          command: |
            THISVERSION=$( python3 -c 'import funcworks; print(funcworks.__version__)' )
            THISVERSION="${CIRCLE_TAG:-$THISVERSION}"
            DOCKERVERSION=$(docker run --rm adamkimbler/funcworks:latest --version \
                           | tail -n 1 | sed -e 's/.*fit/fit/' -e 's/[\r\n]//g')
            echo "$THISVERSION"
            echo "$DOCKERVERSION"
            # test "$DOCKERVERSION" = "funcworks v$THISVERSION.dirty"
      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save adamkimbler/funcworks:latest \
            | pigz -2 -p 3 > /tmp/cache/docker.tar.gz
      - persist_to_workspace:
          root: /tmp
          paths:
            - src/funcworks
      - save_cache:
          key: docker-v0-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
          paths:
            - /tmp/cache/docker.tar.gz

  cache_test_data:
    docker:
      - image: markiewicz/datalad:0.0.1
    working_directory: /tmp/data
    steps:
      - checkout:
          path: /tmp/src
      - restore_cache:
          keys:
            - ds003-v0-{{ .Branch }}-
            - ds003-v0-master-
            - ds003-v0-
      - run:
          name: Set git ID
          command: |
            git config --global user.name 'Adam Kimbler'
            git config --global user.email 'akimbler@fiu.edu'
      - run:
          name: Install fMRIPrep derivatives of ds000003
          command: |
            datalad install -r ///labs/poldrack/ds003_fmriprep
            datalad update ds003_fmriprep/
            datalad get ds003_fmriprep/sub-0{1,2,3}/func/*_space-MNI152NLin2009cAsym_desc-*.nii.gz \
                        ds003_fmriprep/sub-0{1,2,3}/func/*_desc-confounds_*.tsv \
                        ds003_fmriprep/dataset_description.json \
                        ds003_fmriprep/sub-*/*/*.json
      - run:
          name: Download a model for ds000003
          command: |
              mkdir -p ds003_models
              cp /tmp/src/examples/models/ds000003/models/model-001_smdl.json ds003_models/
      - save_cache:
         key: ds003-v0-{{ .Branch }}-{{ .BuildNum }}
         paths:
            - /tmp/data

  test_ds003:
      machine:
          image: ubuntu-1604:201903-01
      working_directory: /tmp/src/funcworks
      steps:
        - attach_workspace:
            at: /tmp
        - restore_cache:
            keys:
              - docker-v0-{{ .Branch }}-{{ .Revision }}
        - restore_cache:
            keys:
              - ds003-v0-{{ .Branch }}-
              - ds003-v0-master-
              - ds003-v0-
        - run:
            name: Update pyenv
            command: |
                pyenv update
        - run:
            name: Install coverage and codecov
            command: |
                pyenv install 3.8.0
                pyenv local 3.8.0
                python -m pip install -U "coverage<5" codecov
        - run:
            name: Load Docker image layer cache
            no_output_timeout: 30m
            command: |
              docker info
              set +o pipefail
              if [ -f /tmp/cache/docker.tar.gz ]; then
                sudo apt update && sudo apt -y install pigz
                pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
                docker images
              fi
        - run:
            name: Run Funcworks
            no_output_timeout: 2h
            command: |
              mkdir -p /tmp/ds003/work /tmp/ds003/derivatives
              chmod 777 /tmp/ds003/work /tmp/ds003/derivatives
              export CONDA_PREFIX=/opt/miniconda-latest/envs/neuro
              docker run --rm -v /tmp/data/ds003_fmriprep:/data:ro \
                  -v /tmp/ds003/derivatives:/out \
                  -v /tmp/ds003/work:/scratch \
                  -v /tmp/data/ds003_models:/models \
                  -e COVERAGE_FILE=/scratch/.coverage \
                  --entrypoint="/neurodocker/startup.sh" \
                  adamkimbler/funcworks:latest \
                  coverage run \
                  --rcfile /src/funcworks/docker/multiproc.coveragerc \
                  $CONDA_PREFIX/bin/funcworks /data/sourcedata /out dataset \
                  -d /data -m /models/model-001_smdl.json -w /scratch \
                  --participant-label 01 02 03 --space MNI152NLin2009cAsym \
                  --n-cpus 2 --mem-gb 4 -vv
        - run:
            name: Run Funcworks Database-file
            no_output_timeout: 2h
            command: |
              mkdir -p /tmp/ds003/work_dbf
              chmod 777 /tmp/ds003/work_dbf /tmp/ds003/derivatives
              export CONDA_PREFIX=/opt/miniconda-latest/envs/neuro
              docker run --rm -v /tmp/data/ds003_fmriprep:/data \
                  -v /tmp/ds003/derivatives:/out \
                  -v /tmp/ds003/work_dbf:/scratch \
                  -v /tmp/data/ds003_models:/models \
                  -e COVERAGE_FILE=/scratch/.coverage.database-file \
                  --entrypoint="/neurodocker/startup.sh" \
                  adamkimbler/funcworks:latest \
                  coverage run \
                  --rcfile /src/funcworks/docker/multiproc.coveragerc \
                  $CONDA_PREFIX/bin/funcworks /data/sourcedata /out dataset \
                  -d /data -m /models/model-001_smdl.json -w /scratch \
                  --participant-label 01 02 03 --space MNI152NLin2009cAsym \
                  --n-cpus 2 --database-path /out/pybidsdb -vv
        - run:
            name: Run Funcworks Database-file_exists
            no_output_timeout: 2h
            command: |
              mkdir -p /tmp/ds003/work_dbf2
              chmod 777 /tmp/ds003/work_dbf2 /tmp/ds003/derivatives
              export CONDA_PREFIX=/opt/miniconda-latest/envs/neuro
              docker run --rm -v /tmp/data/ds003_fmriprep:/data \
                  -v /tmp/ds003/derivatives:/out \
                  -v /tmp/ds003/work_dbf2:/scratch \
                  -v /tmp/data/ds003_models:/models \
                  -e COVERAGE_FILE=/scratch/.coverage.database-file \
                  --entrypoint="/neurodocker/startup.sh" \
                  adamkimbler/funcworks:latest \
                  coverage run \
                  --rcfile /src/funcworks/docker/multiproc.coveragerc \
                  $CONDA_PREFIX/bin/funcworks /data/sourcedata /out dataset \
                  -d /data -m /models/model-001_smdl.json -w /scratch \
                  --participant-label 01 02 03 --space MNI152NLin2009cAsym \
                  --n-cpus 2 --database-path /out/pybidsdb -vv
        - run:
            name: Combine coverage and submit
            command: |
                pyenv local 3.6.3
                python -m coverage combine \
                  --rcfile /tmp/src/funcworks/docker/multiproc.coveragerc \
                  /tmp/ds003/work/.coverage.* \
                  /tmp/ds003/work_dbf*/.coverage.*
                sed -i -e 's/.opt.miniconda-latest.envs.neuro.lib.python3.6.site-packages/\/tmp\/src\/funcworks/g' .coverage
                python -m coverage xml
                python -m codecov --file coverage.xml --flags ds003 -e CIRCLE_JOB
        - store_artifacts:
            path: /tmp/ds003

workflows:
  version: 2.1
  build_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: /doc\/.*/
            tags:
              only: /.*/
      - cache_test_data:
          filters:
            branches:
              ignore: /doc\/.*/
            tags:
              only: /.*/
      - test_ds003:
          requires:
            - build
            - cache_test_data
  style_check:
    jobs:
      - style_check
